CREATE TABLE IF NOT EXISTS `#__js_ticket_attachments` (
	`id` int(11) NOT NULL AUTO_INCREMENT, 
	`ticketid` int(11) DEFAULT NULL, 
	`replyattachmentid` int(11) DEFAULT NULL, 
	`filesize` varchar(32) DEFAULT NULL, 
	`filename` varchar(128) DEFAULT NULL, 
	`filekey` varchar(128) DEFAULT NULL, 
	`deleted` tinyint(1) DEFAULT NULL, 
	`status` tinyint(1) DEFAULT NULL, 
	`created` datetime DEFAULT NULL, 
	PRIMARY KEY (`id`) ) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `#__js_ticket_config` (`configname` varchar(100) NOT NULL DEFAULT '', 
	`configvalue` TEXT DEFAULT NULL, 
	`configfor` varchar(50) DEFAULT NULL, PRIMARY KEY (`configname`), FULLTEXT KEY `config_name` (`configname`), FULLTEXT KEY `config_for` (`configfor`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `#__js_ticket_config` VALUES 
('version', '126', 'version'),
('versiontype', 'free', 'version'),
('priority', '15', 'default'),
('ticket_per_email', '25', 'ticket'),
('cplink_myticket_staff', '1', 'cplink'),
('reopened_ticket_auto_assign', '1', 'ticket'),
('assigned_ticket_open_queue', '1', 'ticket'),
('answered_ticket_open_queue', '1', 'ticket'),
('alert_email', '1', 'email'),
('admin_email', '1', 'email'),
('ticket_department_transfer_admin', '1', 'email'),
('ticket_ban_email_admin', '1', 'email'),
('ticket_ban_email_user', '1', 'email'),
('new_ticket_admin', '1', 'email'),
('new_ticket_staff', '1', 'email'),
('new_staff_admin', '1', 'email'),
('new_group_admin', '1', 'email'),
('new_depatment_admin', '1', 'email'),
('new_help_topic_admin', '1', 'email'),
('theme', 'golden/css/jsticketsgolden.css', 'default'),
('title', 'JS Support Ticket', 'default'),
('data_directory', 'jssupportticketdata', 'default'),
('fr_cr_txb', '<br>&copy;Copyright 2008 - 2010, <a href="http://www.burujsolutions.com" target="_blank">Buruj Solutions </a> ', 'default'),
('backuponuninstall', '1', 'default'),
('offline','0','default'),
('offline_text','system down please come back soon.','default'),
('ticket_lock_admin','1','email'),
('payment_method','paypal','payment'),
('payment_shopingurl','','payment'),
('payment_successefulurl','','payment'),
('payment_cancelurl','','payment'),
('payment_paypalaccount','','payment'),
('payment_showdescription','1','payment'),
('payment_description','Description','payment'),
('payment_showfooter','1','payment'),
('payment_currency','USD','payment'),
('payment_authtoken','','payment'),
('payment_test_mode','1','payment'),
('date_format','d-m-Y','default'),
('ticket_unbanemail_staff','1','email'),
('ticket_unbanemail_user','1','email'),
('ticket_unbanemail_admin','1','email'),
('ticket_ban_and_close_staff','1','email'),
('ticket_ban_and_close_user','1','email'),
('ticket_ban_and_close_admin','1','email'),
('mailfromname','JS Tickets','email'),
('ticket_response_staff_user','1','email'),
('ticket_response_staff_staff','1','email'),
('ticket_response_staff_admin','1','email'),
('ticket_reply_user_admin','1','email'),
('ticket_department_transfer_user','1','email'),
('ticket_reassign_admin','1','email'),
('ticket_reassign_staff','1','email'),
('ticket_reassign_user','1','email'),
('ticket_close_admin','1','email'),
('ticket_close_staff','1','email'),
('ticket_close_user','1','email'),
('ticket_delete_admin','1','email'),
('ticket_delete_staff','1','email'),
('ticket_delete_user','1','email'),
('ticket_overdue_admin','1','email'),
('ticket_overdue_staff','1','email'),
('ticket_overdue_user', '1', 'email'),
('system_email','13','email'),
('cur_location', '1', 'default'),
('fr_cr_txa', '<img src="components/com_jsjobs/images/jsjobs_logo_small.png" width="65">&nbsp;&nbsp;&nbsp;Powered by <a href="https://www.joomsky.com" target="_blank">Joom Sky</a>', 'default'),
('api_primary', 'a2d09c7d76fced01f8be4b1f4cce8bec', 'api'),
('api_secondary', '', 'api'),
('filesize', '3072', 'default'),
('fileextension', 'doc,docx,odt,pdf,txt,png,jpeg,jpg,zip', 'default'),
('ticket_department_transfer_staff', '1', 'email'),
('ticket_ban_email_staff', '1', 'email'),
('ticket_reply_user_staff', '1', 'email'),
('staff_knowledgebase_articles', '1', 'knowledgebase'),
('staff_knowledgebase_category', '1', 'knowledgebase'),
('knowledgebase_articles_per_row', '2', 'knowledgebase'),
('banemail_new_ticket_admin', '1', 'email'),
('noofattachment', '5', 'default'),
('can_append_message', '1', 'email'),
('visitor_can_create_ticket', '0', 'default'),
('ticket_reopen_within_days', '5', 'ticket'),
('show_captcha_visitor_form_ticket', '1', 'default'),
('defaultalert', '0', 'default'),
('tvalue', '0', 'version'),
('ticket_overdue_indays', '5', 'default'),
('knowledgebase_enable', '1', 'default'),
('ticket_auto_close_indays', '5', 'default'),
('cplink_openticket_staff', '1', 'cplink'),
('ticket_reply_user_user', '1', 'email'),
('ticket_lock_user', '1', 'email'),
('ticket_lock_staff', '1', 'email'),
('cplink_addrole_staff', '0', 'cplink'),
('cplink_roles_staff', '1', 'cplink'),
('cplink_addstaff_staff', '0', 'cplink'),
('cplink_staff_staff', '1', 'cplink'),
('cplink_adddepartment_staff', '0', 'cplink'),
('cplink_department_staff', '1', 'cplink'),
('cplink_addcategory_staff', '0', 'cplink'),
('cplink_category_staff', '1', 'cplink'),
('cplink_addkb_staff', '0', 'cplink'),
('cplink_kb_staff', '1', 'cplink'),
('cplink_adddownload_staff', '0', 'cplink'),
('cplink_download_staff', '1', 'cplink'),
('cplink_addannouncement_staff', '0', 'cplink'),
('cplink_announcement_staff', '1', 'cplink'),
('cplink_addfaq_staff', '0', 'cplink'),
('cplink_faq_staff', '1', 'cplink'),
('cplink_mail_staff', '1', 'cplink'),
('cplink_profile_staff', '1', 'cplink'),
('tplink_home_staff', '1', 'tplink'),
('tplink_ticket_staff', '1', 'tplink'),
('tplink_kb_staff', '1', 'tplink'),
('tplink_announcement_staff', '1', 'tplink'),
('tplink_download_staff', '1', 'tplink'),
('tplink_faq_staff', '1', 'tplink'),
('cplink_openticket_user', '1', 'cplink'),
('cplink_myticket_user', '1', 'cplink'),
('cplink_checkstatus_user', '1', 'cplink'),
('cplink_download_user', '1', 'cplink'),
('cplink_announcement_user', '1', 'cplink'),
('cplink_faq_user', '1', 'cplink'),
('cplink_kb_user', '1', 'cplink'),
('tplink_home_user', '1', 'tplink'),
('tplink_ticket_user', '1', 'tplink'),
('tplink_kb_user', '1', 'tplink'),
('tplink_announcement_user', '1', 'tplink'),
('tplink_download_user', '1', 'tplink'),
('tplink_faq_user', '1', 'tplink'),
('show_count_tickets', '1', 'default'),
('maximum_ticket', '100', 'default'),
('ticket_unlock_user', '1', 'email'),
('ticket_unlock_admin', '1', 'email'),
('ticket_unlock_staff', '1', 'email'),
('unban_email_admin', '1', 'email'),
('unban_email_staff', '1', 'email'),
('unban_email_user', '1', 'email'),
('controlpanel_column_count', '3', 'default'),
('tve_enabled', '0', 'ticketviaemail'),
('cronjob_time', '', 'default'),
('tve_attachment', '1', 'ticketviaemail'),
('tve_mailreadtype', '1', 'ticketviaemail'),
('tve_emailpassword', '', 'ticketviaemail'),
('tve_emailaddress', '', 'ticketviaemail'),
('tve_hostname', '', 'ticketviaemail'),
('tve_hosttype', '1', 'ticketviaemail'),
('serialnumber', '', 'hostdata'),
('hostdata', '', 'hostdata'),
('zvdk', '', 'hostdata'),
('captcha_selection', '2', 'default'),
('owncaptcha_calculationtype', '1', 'default'),
('owncaptcha_totaloperand', '2', 'default'),
('owncaptcha_subtractionans', '1', 'default'),
('new_ticket_message', '', 'default'),
('tve_ssl','2','ticketviaemail'), 
('tve_hostportnumber','','ticketviaemail'), 
('maximum_open_tickets','100','default'), 
('ticket_priority_user','1','email'), 
('ticket_priority_admin','1','email'), 
('ticket_priority_staff','1','email'),
('ticketid_sequence','1','default'),
('ticket_progress_admin', '1', 'email'),
('ticket_progress_staff', '1', 'email'),
('ticket_progress_user', '1', 'email'),
('print_ticket_user', '0', 'ticket'),
('cplink_staff_report_staff', '1', 'cplink'),
('last_step_updater', '1152', 'default'),
('last_version', '106', 'default'),
('cplink_department_report_staff', '1', 'cplink'),
('visitor_message','Thank You for contacting us. A support ticket request has been created, A representative will be getting back to you shortly.<br/>\r\nSupport Team','default'),
('ticket_overdue_type','1','default'), 
('reply_to_closed_ticket','1','default'), 
('feedback_email_delay_type','1','default'), 
('feedback_email_delay','3','default'), 
('ticket_feedback_user','1','default'), 
('cplink_feedback_staff','1','default'),
('feedback_thanks_message','Thank you for providing your feedback. We appreciate the time you have taken and will actively use it to improve our services to you','default'),
('read_utf_ticket_via_email','1','ticketviaemail'),
('cplink_latesttickets_staff', '1', 'cplink'),
('cplink_totalcount_staff', '1', 'cplink'),
('cplink_ticketstats_staff', '1', 'cplink'),
('show_header', '1', 'default'),
('cplink_userdata_user', '1', 'cplink'),
('cplink_userdata_staff', '1', 'cplink'),
('erase_data_request_user', '1', 'email'),
('erase_data_request_admin', '1', 'email'),
('delete_user_data', '1', 'email'),
('private_credentials_secretkey', 'privatecredentials', 'privatecredentials'),
('tickets_sorting', '1', 'default'),
('maximum_ticket_interval_time', '1', 'default');



CREATE TABLE IF NOT EXISTS `#__js_ticket_departments` (
	`id` int(11) NOT NULL AUTO_INCREMENT, 
	`emailtemplateid` int(11) DEFAULT NULL, 
	`emailid` int(11) DEFAULT NULL, 
	`autoresponceemailid` int(11) DEFAULT NULL, 
	`managerid` int(11) DEFAULT NULL, 
	`departmentname` varchar(32) DEFAULT NULL, 
	`departmentsignature` text DEFAULT NULL, 
	`ispublic` tinyint(1) DEFAULT NULL, 
	`isdefault` tinyint(1) DEFAULT NULL, 
	`sendemail` tinyint(1) DEFAULT NULL, 
	`ticketautoresponce` tinyint(1) DEFAULT NULL, 
	`messageautoresponce` tinyint(1) DEFAULT NULL, 
	`canappendsignature` tinyint(1) DEFAULT NULL, 
	`update` datetime DEFAULT NULL, 
	`created` datetime DEFAULT NULL, 
	`status` tinyint(1) DEFAULT NULL, 
	PRIMARY KEY (`id`) ) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

INSERT INTO `#__js_ticket_departments` VALUES (1,NULL,1,NULL,NULL,'Support','--Support Signature--',1,1,0,0,0,1,now(),now(),1);

CREATE TABLE IF NOT EXISTS `#__js_ticket_email` (
	`id` int(11) NOT NULL AUTO_INCREMENT, 
	`autoresponce` tinyint(1) DEFAULT NULL, 
	`priorityid` int(11) DEFAULT NULL, 
	`departmentid` int(11) DEFAULT NULL, 
	`email` varchar(125) DEFAULT NULL, 
	`name` varchar(32) DEFAULT NULL, 
	`uid` int(11) DEFAULT NULL, 
	`password` varchar(125) DEFAULT NULL COMMENT '	', 
	`status` tinyint(1) DEFAULT NULL, 
	`smtpemailauth` TINYINT DEFAULT NULL,
	`mailhost` varchar(125) DEFAULT NULL, 
	`mailprotocol` enum('pop','map') DEFAULT NULL, 
	`mailencryption` enum('NONE','SSL') DEFAULT NULL, 
	`mailport` smallint(6) DEFAULT NULL, 
	`mailfetchfrequency` tinyint(3) DEFAULT NULL, 
	`mailfetchmaximum` tinyint(4) DEFAULT NULL, 
	`maildeleted` tinyint(1) DEFAULT NULL, 
	`mailerrors` tinyint(3) DEFAULT NULL, 
	`maillasterror` datetime DEFAULT NULL, 
	`maillastfetch` datetime DEFAULT NULL, 
	`smtpactive` tinyint(1) DEFAULT NULL, 
	`smtphosttype` INT DEFAULT NULL,
	`smtphost` varchar(125) DEFAULT NULL, 
	`smtpport` smallint(6) DEFAULT NULL, 
	`smtpsecure` tinyint(1) DEFAULT NULL, 
	`smtpauthencation` tinyint(1) DEFAULT NULL, 
	`created` datetime DEFAULT NULL, 
	`update` datetime DEFAULT NULL, 
	PRIMARY KEY (`id`) ) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `#__js_ticket_emailtemplates` (
	`id` int(11) NOT NULL AUTO_INCREMENT, 
	`templatefor` varchar(50) DEFAULT NULL, 
	`title` varchar(50) DEFAULT NULL, 
	`subject` varchar(255) DEFAULT NULL, 
	`body` text DEFAULT NULL, 
	`created` datetime DEFAULT NULL, 
	`status` tinyint(1) DEFAULT NULL, 
	PRIMARY KEY (`id`) ) ENGINE=MyISAM AUTO_INCREMENT=25 DEFAULT CHARSET=utf8;

INSERT INTO `#__js_ticket_emailtemplates` (`id`, `templatefor`, `title`, `subject`, `body`, `created`, `status`) VALUES
(1, 'ticket-new', '', 'JS Support Ticket: New Ticket Received [{TRACKINGID}]', '<div style=\"background-color: #f7f7f7; margin: 0; padding: 70px 0; width: 100%;\">\r\n<div style=\"border: 3px dotted #ebecec; width: 600px; display: block; margin: 0 auto; background: #fff;\">\r\n<div style=\"float: left; width: 100%; background: #576cf1; background-repeat: no-repeat, no-repeat, no-repeat; background-position: top left, top right, center center; margin-bottom: 20px;\">\r\n<div style=\"padding: 22px 20px; background: #3e4095; color: #fff; font-size: 18px; font-weight: bold; text-transform: capitalize;\">\r\n<div style=\"display: inline-block;\">JS Support Ticket</div>\r\n<div style=\"float: right; font-weight: bold; font-size: 18px; color: #fff;\">Dear {USERNAME},</div>\r\n</div>\r\n<div style=\"padding: 40px 30px; text-align: center; font-weight: bold; color: #fff; text-transform: capitalize; font-size: 22px;\">New Ticket Received</div>\r\n</div>\r\n<div style=\"padding: 0px;\">\r\n<div style=\"padding-bottom: 20px; border-bottom: 1px solid #dbdbda; background: #f9f9f9; color: #4b4b4d; margin-bottom: 40px;\">\r\n<div style=\"color: #727376; line-height: 2; padding: 17px; text-align: center;\">Your support ticket <strong>{SUBJECT}</strong> has been submitted. We try to reply to all tickets as soon as possible, usually within 24 hours.</div>\r\n</div>\r\n<div style=\"padding: 20px 20px 10px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda; background: #f9f9f9;\">\r\n<div style=\"font-weight: bold; font-size: 16px; margin-bottom: 10px; color: #4b4b4d;\">Tracking ID: <span class=\"js-email-paramater\">{TRACKINGID}</span></div>\r\n</div>\r\n<div style=\"padding: 20px 20px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda;\">Email ID: {EMAIL}</div>\r\n<div style=\"padding: 20px 20px;\">Ticket message: {MESSAGE}</div>\r\n<div style=\"padding: 20px 20px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda;\">You can view the status of your ticket here:<br />{TICKETURL}</div>\r\n<div style=\"padding: 20px 20px; border-bottom: 1px solid #dbdbda;\">You will receive an e-mail notification when our staff replies to your ticket.</div>\r\n<div style=\"background: #fef2ef; padding: 15px; margin: 20px; border: 1px solid #eba7a8;\">\r\n<div style=\"font-weight: bold; font-size: 14px; margin-bottom: 5px; color: #983133; text-transform: uppercase;\">Do not reply TO this E-Mail</div>\r\n<div style=\"color: #727376; line-height: 2;\">This is an automated e-mail message sent from our support system. Do not reply to this e-mail as we cannot receive your reply!</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>', '2012-07-20 11:09:00', 1),
(6, 'reassign-tk', NULL, 'JS Support Ticket: Reassign Tickets', '<div style=\"background-color: #f7f7f7; margin: 0; padding: 70px 0; width: 100%;\">\r\n<div style=\"border: 3px dotted #ebecec; width: 600px; display: block; margin: 0 auto; background: #fff;\">\r\n<div style=\"float: left; width: 100%; background: #567cf1; background-repeat: no-repeat, no-repeat, no-repeat; background-position: top left, top right, center center; margin-bottom: 20px;\">\r\n<div style=\"padding: 22px 20px; background: #3e4095; color: #fff; font-size: 18px; font-weight: bold; text-transform: capitalize;\">\r\n<div style=\"display: inline-block;\">JS Support Ticket</div>\r\n<div style=\"float: right; font-weight: bold; font-size: 18px; color: #fff;\"> </div>\r\n</div>\r\n<div style=\"padding: 40px 30px; text-align: center; font-weight: bold; color: #fff; text-transform: capitalize; font-size: 22px;\">Success: Ticket Reassign</div>\r\n</div>\r\n<div style=\"padding: 0px;\">\r\n<div style=\"padding-bottom: 20px; border-bottom: 1px solid #dbdbda; background: #f9f9f9; color: #4b4b4d; margin-bottom: 40px;\">\r\n<div style=\"color: #727376; line-height: 2; padding: 17px; text-align: center;\">Your ticket has been successfully Reassign! Ticket ID:<span class=\"js-email-paramater\">{TRACKINGID}</span> is Reassign to Staff Member:<span class=\"js-email-paramater\">{STAFF_MEMBER_NAME}</span></div>\r\n</div>\r\n<div style=\"padding: 20px 20px 10px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda; background: #f9f9f9;\">\r\n<div style=\"font-weight: bold; font-size: 16px; margin-bottom: 10px; color: #4b4b4d;\">Ticket Subject : {SUBJECT}</div>\r\n</div>\r\n<div style=\"padding: 20px 20px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda;\">You can manage this ticket here:<br /><span class=\"js-email-paramater\">{TICKETURL}</span></div>\r\n<div style=\"background: #fef2ef; padding: 15px; margin: 20px; border: 1px solid #eba7a8;\">\r\n<div style=\"font-weight: bold; font-size: 14px; margin-bottom: 5px; color: #983133; text-transform: uppercase;\">Do not reply TO this E-Mail</div>\r\n<div style=\"color: #727376; line-height: 2;\">This is an automated e-mail message sent from our support system. Do not reply to this e-mail as we cannot receive your reply!</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>', '2012-07-22 07:17:43', NULL),
(7, 'close-tk', NULL, 'JS Support Ticket:  Close Tickets', '<div style=\"background-color: #f7f7f7; margin: 0; padding: 70px 0; width: 100%;\">\r\n<div style=\"border: 3px dotted #ebecec; width: 600px; display: block; margin: 0 auto; background: #fff;\">\r\n<div style=\"float: left; width: 100%; background: #576cf1; background-repeat: no-repeat, no-repeat, no-repeat; background-position: top left, top right, center center; margin-bottom: 20px;\">\r\n<div style=\"padding: 22px 20px; background: #3e4095; color: #fff; font-size: 18px; font-weight: bold; text-transform: capitalize;\">\r\n<div style=\"display: inline-block;\">JS Support Ticket</div>\r\n<div style=\"float: right; font-weight: bold; font-size: 18px; color: #fff;\"> </div>\r\n</div>\r\n<div style=\"padding: 40px 30px; text-align: center; font-weight: bold; color: #fff; text-transform: capitalize; font-size: 22px;\">Ticket Close</div>\r\n</div>\r\n<div style=\"padding: 0px;\">\r\n<div style=\"padding-bottom: 20px; border-bottom: 1px solid #dbdbda; background: #f9f9f9; color: #4b4b4d; margin-bottom: 40px;\">\r\n<div style=\"color: #727376; line-height: 2; padding: 17px; text-align: center;\">Ticket ID:<span class=\"js-email-paramater\">{TRACKINGID}</span> is Closed.</div>\r\n</div>\r\n<div style=\"padding: 20px 20px 10px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda; background: #f9f9f9;\">\r\n<div style=\"font-weight: bold; font-size: 16px; margin-bottom: 10px; color: #4b4b4d;\">Ticket Subject : {SUBJECT}</div>\r\n</div>\r\n<div style=\"padding: 20px 20px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda;\">You can manage this ticket here:<br /><span class=\"js-email-paramater\">{TICKETURL}</span></div>\r\n<div style=\"background: #fef2ef; padding: 15px; margin: 20px; border: 1px solid #eba7a8;\">\r\n<div style=\"font-weight: bold; font-size: 14px; margin-bottom: 5px; color: #983133; text-transform: uppercase;\">Do not reply TO this E-Mail</div>\r\n<div style=\"color: #727376; line-height: 2;\">This is an automated e-mail message sent from our support system. Do not reply to this e-mail as we cannot receive your reply!</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>', '2012-07-22 07:17:54', NULL),
(8, 'delete-tk', NULL, 'JS Support Ticket:  Delete Ticket', '<div style=\"background-color: #f7f7f7; margin: 0; padding: 70px 0; width: 100%;\">\r\n<div style=\"border: 3px dotted #ebecec; width: 600px; display: block; margin: 0 auto; background: #fff;\">\r\n<div style=\"float: left; width: 100%; background: #576cf1; background-repeat: no-repeat, no-repeat, no-repeat; background-position: top left, top right, center center; margin-bottom: 20px;\">\r\n<div style=\"padding: 22px 20px; background: #3e4095; color: #fff; font-size: 18px; font-weight: bold; text-transform: capitalize;\">\r\n<div style=\"display: inline-block;\">JS Support Ticket</div>\r\n<div style=\"float: right; font-weight: bold; font-size: 18px; color: #fff;\"> </div>\r\n</div>\r\n<div style=\"padding: 40px 30px; text-align: center; font-weight: bold; color: #fff; text-transform: capitalize; font-size: 22px;\">Ticket Deleted</div>\r\n</div>\r\n<div style=\"padding: 0px;\">\r\n<div style=\"padding-bottom: 20px; border-bottom: 1px solid #dbdbda; background: #f9f9f9; color: #4b4b4d; margin-bottom: 40px;\">\r\n<div style=\"color: #727376; line-height: 2; padding: 17px; text-align: center;\">Ticket ID:<span class=\"js-email-paramater\">{TRACKINGID}</span> is Deleted.</div>\r\n</div>\r\n<div style=\"padding: 20px 20px 10px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda; background: #f9f9f9;\">\r\n<div style=\"font-weight: bold; font-size: 16px; margin-bottom: 10px; color: #4b4b4d;\">Ticket Subject : {SUBJECT}</div>\r\n</div>\r\n<div style=\"background: #fef2ef; padding: 15px; margin: 20px; border: 1px solid #eba7a8;\">\r\n<div style=\"font-weight: bold; font-size: 14px; margin-bottom: 5px; color: #983133; text-transform: uppercase;\">Do not reply TO this E-Mail</div>\r\n<div style=\"color: #727376; line-height: 2;\">This is an automated e-mail message sent from our support system. Do not reply to this e-mail as we cannot receive your reply!</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>', '2012-07-22 07:18:05', NULL),
(9, 'moverdue-tk', NULL, 'JS Support Ticket:  Ticket Mark Overdue ', '<div style=\"background-color: #f7f7f7; margin: 0; padding: 70px 0; width: 100%;\">\r\n<div style=\"border: 3px dotted #ebecec; width: 600px; display: block; margin: 0 auto; background: #fff;\">\r\n<div style=\"float: left; width: 100%; background: #576cf1; background-repeat: no-repeat, no-repeat, no-repeat; background-position: top left, top right, center center; margin-bottom: 20px;\">\r\n<div style=\"padding: 22px 20px; background: #3e4095; color: #fff; font-size: 18px; font-weight: bold; text-transform: capitalize;\">\r\n<div style=\"display: inline-block;\">JS Support Ticket</div>\r\n<div style=\"float: right; font-weight: bold; font-size: 18px; color: #fff;\">Hi,</div>\r\n</div>\r\n<div style=\"padding: 40px 30px; text-align: center; font-weight: bold; color: #fff; text-transform: capitalize; font-size: 22px;\">Ticket Mark Overdue</div>\r\n</div>\r\n<div style=\"padding: 0px;\">\r\n<div style=\"padding-bottom: 20px; border-bottom: 1px solid #dbdbda; background: #f9f9f9; color: #4b4b4d; margin-bottom: 40px;\">\r\n<div style=\"color: #727376; line-height: 2; padding: 17px; text-align: center;\">Ticket ID:<span class=\"js-email-paramater\">{TRACKINGID}</span> is Mark overdue.</div>\r\n</div>\r\n<div style=\"padding: 20px 20px 10px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda; background: #f9f9f9;\">\r\n<div style=\"font-weight: bold; font-size: 16px; margin-bottom: 10px; color: #4b4b4d;\">Ticket Subject : {SUBJECT}</div>\r\n</div>\r\n<div style=\"padding: 20px 20px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda;\">You can manage this ticket here:<br /><span class=\"js-email-paramater\">{TICKETURL}</span></div>\r\n<div style=\"background: #fef2ef; padding: 15px; margin: 20px; border: 1px solid #eba7a8;\">\r\n<div style=\"font-weight: bold; font-size: 14px; margin-bottom: 5px; color: #983133; text-transform: uppercase;\">Do not reply TO this E-Mail</div>\r\n<div style=\"color: #727376; line-height: 2;\">This is an automated e-mail message sent from our support system. Do not reply to this e-mail as we cannot receive your reply!</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>', '2012-07-22 07:18:12', NULL),
(10, 'banemail-tk', '', 'JS Support Ticket:  Ban new email', '<div style=\"background-color: #f7f7f7; margin: 0; padding: 70px 0; width: 100%;\">\r\n<div style=\"border: 3px dotted #ebecec; width: 600px; display: block; margin: 0 auto; background: #fff;\">\r\n<div style=\"float: left; width: 100%; background: #576cf1; background-repeat: no-repeat, no-repeat, no-repeat; background-position: top left, top right, center center; margin-bottom: 20px;\">\r\n<div style=\"padding: 22px 20px; background: #3e4095; color: #fff; font-size: 18px; font-weight: bold; text-transform: capitalize;\">\r\n<div style=\"display: inline-block;\">JS Support Ticket</div>\r\n<div style=\"float: right; font-weight: bold; font-size: 18px; color: #fff;\">Hi,</div>\r\n</div>\r\n<div style=\"padding: 40px 30px; text-align: center; font-weight: bold; color: #fff; text-transform: capitalize; font-size: 22px;\">Email Baned</div>\r\n</div>\r\n<div style=\"padding: 0px;\">\r\n<div style=\"padding-bottom: 20px; border-bottom: 1px solid #dbdbda; background: #f9f9f9; color: #4b4b4d; margin-bottom: 40px;\">\r\n<div style=\"color: #727376; line-height: 2; padding: 17px; text-align: center;\">This email <span class=\"js-email-paramater\">{EMAIL_ADDRESS}</span> is Baned.</div>\r\n</div>\r\n<div style=\"background: #fef2ef; padding: 15px; margin: 20px; border: 1px solid #eba7a8;\">\r\n<div style=\"font-weight: bold; font-size: 14px; margin-bottom: 5px; color: #983133; text-transform: uppercase;\">Do not reply TO this E-Mail</div>\r\n<div style=\"color: #727376; line-height: 2;\">This is an automated e-mail message sent from our support system. Do not reply to this e-mail as we cannot receive your reply!</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>', '2012-07-22 07:18:20', NULL),
(11, 'deptrans-tk', NULL, 'JS Support Ticket:  Ticket transfer to department {DEPARTMENT_TITLE}', '<div style=\"background-color: #f7f7f7; margin: 0; padding: 70px 0; width: 100%;\">\r\n<div style=\"border: 3px dotted #ebecec; width: 600px; display: block; margin: 0 auto; background: #fff;\">\r\n<div style=\"float: left; width: 100%; background: #576cf1; background-repeat: no-repeat, no-repeat, no-repeat; background-position: top left, top right, center center; margin-bottom: 20px;\">\r\n<div style=\"padding: 22px 20px; background: #3e4595; color: #fff; font-size: 18px; font-weight: bold; text-transform: capitalize;\">\r\n<div style=\"display: inline-block;\">JS Support Ticket</div>\r\n<div style=\"float: right; font-weight: bold; font-size: 18px; color: #fff;\"> </div>\r\n</div>\r\n<div style=\"padding: 40px 30px; text-align: center; font-weight: bold; color: #fff; text-transform: capitalize; font-size: 22px;\">Ticket transfer to department</div>\r\n</div>\r\n<div style=\"padding: 0px;\">\r\n<div style=\"padding-bottom: 20px; border-bottom: 1px solid #dbdbda; background: #f9f9f9; color: #4b4b4d; margin-bottom: 40px;\">\r\n<div style=\"color: #727376; line-height: 2; padding: 17px; text-align: center;\">Ticket ID: <span class=\"js-email-paramater\">{TRACKINGID}</span> is transfer to department <span class=\"js-email-paramater\">{DEPARTMENT_TITLE}</span>.</div>\r\n</div>\r\n<div style=\"padding: 20px 20px 10px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda; background: #f9f9f9;\">\r\n<div style=\"font-weight: bold; font-size: 16px; margin-bottom: 10px; color: #4b4b4d;\">Ticket Subject : {SUBJECT}</div>\r\n</div>\r\n<div style=\"background: #fef2ef; padding: 15px; margin: 20px; border: 1px solid #eba7a8;\">\r\n<div style=\"font-weight: bold; font-size: 14px; margin-bottom: 5px; color: #983133; text-transform: uppercase;\">Do not reply TO this E-Mail</div>\r\n<div style=\"color: #727376; line-height: 2;\">This is an automated e-mail message sent from our support system. Do not reply to this e-mail as we cannot receive your reply!</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>', '2012-07-22 07:18:29', NULL),
(12, 'banemailcloseticket-tk', NULL, 'JS Support Ticket: Email baned and ticket close', '<div style=\"background-color: #f7f7f7; margin: 0; padding: 70px 0; width: 100%;\">\r\n<div style=\"border: 3px dotted #ebecec; width: 600px; display: block; margin: 0 auto; background: #fff;\">\r\n<div style=\"float: left; width: 100%; background: #576cf1; background-repeat: no-repeat, no-repeat, no-repeat; background-position: top left, top right, center center; margin-bottom: 20px;\">\r\n<div style=\"padding: 22px 20px; background: #3e4595; color: #fff; font-size: 18px; font-weight: bold; text-transform: capitalize;\">\r\n<div style=\"display: inline-block;\">JS Support Ticket</div>\r\n<div style=\"float: right; font-weight: bold; font-size: 18px; color: #fff;\"> </div>\r\n</div>\r\n<div style=\"padding: 40px 30px; text-align: center; font-weight: bold; color: #fff; text-transform: capitalize; font-size: 22px;\">Email Baned and ticket close</div>\r\n</div>\r\n<div style=\"padding: 0px;\">\r\n<div style=\"padding-bottom: 20px; border-bottom: 1px solid #dbdbda; background: #f9f9f9; color: #4b4b4d; margin-bottom: 40px;\">\r\n<div style=\"color: #727376; line-height: 2; padding: 17px; text-align: center;\">This email <span class=\"js-email-paramater\">{EMAIL_ADDRESS}</span> is Baned and ticket ID:<span class=\"js-email-paramater\">{TICKETID}</span> is closed.</div>\r\n</div>\r\n<div style=\"padding: 20px 20px 10px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda; background: #f9f9f9;\">\r\n<div style=\"font-weight: bold; font-size: 16px; margin-bottom: 10px; color: #4b4b4d;\">Ticket Subject : {SUBJECT}</div>\r\n</div>\r\n<div style=\"background: #fef2ef; padding: 15px; margin: 20px; border: 1px solid #eba7a8;\">\r\n<div style=\"font-weight: bold; font-size: 14px; margin-bottom: 5px; color: #983133; text-transform: uppercase;\">Do not reply TO this E-Mail</div>\r\n<div style=\"color: #727376; line-height: 2;\">This is an automated e-mail message sent from our support system. Do not reply to this e-mail as we cannot receive your reply!</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>', '2012-07-22 07:18:37', NULL),
(13, 'unbanemail-tk', NULL, 'JS Support Ticket:  Email Unbaneded', '<div style=\"background-color: #f7f7f7; margin: 0; padding: 70px 0; width: 100%;\">\r\n<div style=\"border: 3px dotted #ebecec; width: 600px; display: block; margin: 0 auto; background: #fff;\">\r\n<div style=\"float: left; width: 100%; background: #576cf1; background-repeat: no-repeat, no-repeat, no-repeat; background-position: top left, top right, center center; margin-bottom: 20px;\">\r\n<div style=\"padding: 22px 20px; background: #3e4095; color: #fff; font-size: 18px; font-weight: bold; text-transform: capitalize;\">\r\n<div style=\"display: inline-block;\">JS Support Ticket</div>\r\n<div style=\"float: right; font-weight: bold; font-size: 18px; color: #fff;\"> </div>\r\n</div>\r\n<div style=\"padding: 40px 30px; text-align: center; font-weight: bold; color: #fff; text-transform: capitalize; font-size: 22px;\">Email Un banned</div>\r\n</div>\r\n<div style=\"padding: 0px;\">\r\n<div style=\"padding-bottom: 20px; border-bottom: 1px solid #dbdbda; background: #f9f9f9; color: #4b4b4d; margin-bottom: 40px;\">\r\n<div style=\"color: #727376; line-height: 2; padding: 17px; text-align: center;\">This email <span class=\"js-email-paramater\">{EMAIL_ADDRESS}</span> is Un banned</div>\r\n</div>\r\n<div style=\"background: #fef2ef; padding: 15px; margin: 20px; border: 1px solid #eba7a8;\">\r\n<div style=\"font-weight: bold; font-size: 14px; margin-bottom: 5px; color: #983133; text-transform: uppercase;\">Do not reply TO this E-Mail</div>\r\n<div style=\"color: #727376; line-height: 2;\">This is an automated e-mail message sent from our support system. Do not reply to this e-mail as we cannot receive your reply!</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>', '2012-07-22 07:18:44', NULL),
(14, 'reply-tk', NULL, 'JS Support Ticket:  Ticket Reply [{TRACKINGID}]', '<div style=\"background-color: #f7f7f7; margin: 0; padding: 70px 0; width: 100%;\">\r\n<div style=\"border: 3px dotted #ebecec; width: 600px; display: block; margin: 0 auto; background: #fff;\">\r\n<div style=\"float: left; width: 100%; background: #576cf1; background-repeat: no-repeat, no-repeat, no-repeat; background-position: top left, top right, center center; margin-bottom: 20px;\">\r\n<div style=\"padding: 22px 20px; background: #3e4095; color: #fff; font-size: 18px; font-weight: bold; text-transform: capitalize;\">\r\n<div style=\"display: inline-block;\">JS Support Ticket</div>\r\n<div style=\"float: right; font-weight: bold; font-size: 18px; color: #fff;\">Hello,</div>\r\n</div>\r\n<div style=\"padding: 40px 30px; text-align: center; font-weight: bold; color: #fff; text-transform: capitalize; font-size: 22px;\">Ticket Reply</div>\r\n</div>\r\n<div style=\"padding: 0px;\">\r\n<div style=\"padding-bottom: 20px; border-bottom: 1px solid #dbdbda; background: #f9f9f9; color: #4b4b4d; margin-bottom: 40px;\">\r\n<div style=\"color: #727376; line-height: 2; padding: 17px; text-align: center;\">A new reply of ticket {SUBJECT} has been submitted.</div>\r\n</div>\r\n<div style=\"padding: 20px 20px 10px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda; background: #f9f9f9;\">\r\n<div style=\"font-weight: bold; font-size: 16px; margin-bottom: 10px; color: #4b4b4d;\">Tracking ID: <span class=\"js-email-paramater\">{TRACKINGID}</span></div>\r\n</div>\r\n<div style=\"padding: 20px 20px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda;\">Email: {EMAIL}</div>\r\n<div style=\"padding: 20px 20px;\">message: {MESSAGE}</div>\r\n<div style=\"padding: 20px 20px; border-top: 1px solid #dbdbda;\">User Name: {USERNAME}</div>\r\n<div style=\"padding: 20px 20px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda;\">You can manage this ticket here:<br /><span class=\"js-email-paramater\">{TICKETURL}</span></div>\r\n<div style=\"background: #fef2ef; padding: 15px; margin: 20px; border: 1px solid #eba7a8;\">\r\n<div style=\"font-weight: bold; font-size: 14px; margin-bottom: 5px; color: #983133; text-transform: uppercase;\">Do not reply TO this E-Mail</div>\r\n<div style=\"color: #727376; line-height: 2;\">This is an automated e-mail message sent from our support system. Do not reply to this e-mail as we cannot receive your reply!</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>', '2012-07-22 07:19:08', NULL),
(15, 'responce-tk', NULL, 'JS Support Ticket:  Staff reply to your ticket [{TRACKINGID}]', '<div style=\"background-color: #f7f7f7; margin: 0; padding: 70px 0; width: 100%;\">\r\n<div style=\"border: 3px dotted #ebecec; width: 600px; display: block; margin: 0 auto; background: #fff;\">\r\n<div style=\"float: left; width: 100%; background: #576cf1; background-repeat: no-repeat, no-repeat, no-repeat; background-position: top left, top right, center center; margin-bottom: 20px;\">\r\n<div style=\"padding: 22px 20px; background: #3e4095; color: #fff; font-size: 18px; font-weight: bold; text-transform: capitalize;\">\r\n<div style=\"display: inline-block;\">JS Support Ticket</div>\r\n<div style=\"float: right; font-weight: bold; font-size: 18px; color: #fff;\">Hello,</div>\r\n</div>\r\n<div style=\"padding: 40px 30px; text-align: center; font-weight: bold; color: #fff; text-transform: capitalize; font-size: 22px;\">Staff reply to your ticket</div>\r\n</div>\r\n<div style=\"padding: 0px;\">\r\n<div style=\"padding-bottom: 20px; border-bottom: 1px solid #dbdbda; background: #f9f9f9; color: #4b4b4d; margin-bottom: 40px;\">\r\n<div style=\"color: #727376; line-height: 2; padding: 17px; text-align: center;\">Staff just reply of your ticket <strong>{SUBJECT}</strong>.</div>\r\n</div>\r\n<div style=\"padding: 20px 20px 10px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda; background: #f9f9f9;\">\r\n<div style=\"font-weight: bold; font-size: 16px; margin-bottom: 10px; color: #4b4b4d;\">Tracking ID: <span class=\"js-email-paramater\">{TRACKINGID}</span></div>\r\n</div>\r\n<div style=\"padding: 20px 20px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda;\">Email: {EMAIL}</div>\r\n<div style=\"padding: 20px 20px;\">message: {MESSAGE}</div>\r\n<div style=\"padding: 20px 20px; border-top: 1px solid #dbdbda;\">User Name: {USERNAME}</div>\r\n<div style=\"padding: 20px 20px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda;\">You can manage this ticket here:<br /><span class=\"js-email-paramater\">{TICKETURL}</span></div>\r\n<div style=\"background: #fef2ef; padding: 15px; margin: 20px; border: 1px solid #eba7a8;\">\r\n<div style=\"font-weight: bold; font-size: 14px; margin-bottom: 5px; color: #983133; text-transform: uppercase;\">Do not reply TO this E-Mail</div>\r\n<div style=\"color: #727376; line-height: 2;\">This is an automated e-mail message sent from our support system. Do not reply to this e-mail as we cannot receive your reply!</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>', '2012-07-22 07:18:52', NULL),
(16, 'ticket-staff', '', 'JS Support Ticket: New Tickets [{TRACKINGID}]', '<div style=\"background-color: #f7f7f7; margin: 0; padding: 70px 0; width: 100%;\">\r\n<div style=\"border: 3px dotted #ebecec; width: 600px; display: block; margin: 0 auto; background: #fff;\">\r\n<div style=\"float: left; width: 100%; background: #576cf1; background-repeat: no-repeat, no-repeat, no-repeat; background-position: top left, top right, center center; margin-bottom: 20px;\">\r\n<div style=\"padding: 22px 20px; background: #3e4095; color: #fff; font-size: 18px; font-weight: bold; text-transform: capitalize;\">\r\n<div style=\"display: inline-block;\">JS Support Ticket</div>\r\n<div style=\"float: right; font-weight: bold; font-size: 18px; color: #fff;\">Dear {USERNAME},</div>\r\n</div>\r\n<div style=\"padding: 40px 30px; text-align: center; font-weight: bold; color: #fff; text-transform: capitalize; font-size: 22px;\">Success: Ticket Submitted</div>\r\n</div>\r\n<div style=\"padding: 0px;\">\r\n<div style=\"padding-bottom: 20px; border-bottom: 1px solid #dbdbda; background: #f9f9f9; color: #4b4b4d; margin-bottom: 40px;\">\r\n<div style=\"color: #727376; line-height: 2; padding: 17px; text-align: center;\">New ticket <strong>{SUBJECT}</strong> has been submitted with the following details.</div>\r\n</div>\r\n<div style=\"padding: 20px 20px 10px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda; background: #f9f9f9;\">\r\n<div style=\"font-weight: bold; font-size: 16px; margin-bottom: 10px; color: #4b4b4d;\">Tracking ID: {TRACKINGID}</div>\r\n</div>\r\n<div style=\"padding: 20px 20px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda;\">Email ID: {EMAIL}</div>\r\n<div style=\"padding: 20px 20px;\">Ticket message: {MESSAGE}</div>\r\n<div style=\"padding: 20px 20px; border-top: 1px solid #dbdbda;\">Help Topic: {HELP_TOPIC}</div>\r\n<div style=\"padding: 20px 20px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda;\">You can view the status of your ticket here:<br />{TICKETURL}</div>\r\n<div style=\"padding: 20px 20px; border-bottom: 1px solid #dbdbda;\">You will receive an e-mail notification when our staff replies to your ticket.</div>\r\n<div style=\"background: #fef2ef; padding: 15px; margin: 20px; border: 1px solid #eba7a8;\">\r\n<div style=\"font-weight: bold; font-size: 14px; margin-bottom: 5px; color: #983133; text-transform: uppercase;\">Do not reply TO this E-Mail</div>\r\n<div style=\"color: #727376; line-height: 2;\">This is an automated e-mail message sent from our support system. Do not reply to this e-mail as we cannot receive your reply!</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>', '2012-07-22 06:43:31', NULL),
(17, 'banemail-trtk', NULL, 'JS Support Ticket: Ban email try to create new ticket', '<div style=\"background-color: #f7f7f7; margin: 0; padding: 70px 0; width: 100%;\">\r\n<div style=\"border: 3px dotted #ebecec; width: 600px; display: block; margin: 0 auto; background: #fff;\">\r\n<div style=\"float: left; width: 100%; background: #576cf1; background-repeat: no-repeat, no-repeat, no-repeat; background-position: top left, top right, center center; margin-bottom: 20px;\">\r\n<div style=\"padding: 22px 20px; background: #3e4095; color: #fff; font-size: 18px; font-weight: bold; text-transform: capitalize;\">\r\n<div style=\"display: inline-block;\">JS Support Ticket</div>\r\n<div style=\"float: right; font-weight: bold; font-size: 18px; color: #fff;\">Hello Admin ,</div>\r\n</div>\r\n<div style=\"padding: 40px 30px; text-align: center; font-weight: bold; color: #fff; text-transform: capitalize; font-size: 22px;\">Ban email try to create new ticket</div>\r\n</div>\r\n<div style=\"padding: 0px;\">\r\n<div style=\"padding-bottom: 20px; border-bottom: 1px solid #dbdbda; background: #f9f9f9; color: #4b4b4d; margin-bottom: 40px;\">\r\n<div style=\"color: #727376; line-height: 2; padding: 17px; text-align: center;\">This email <span class=\"js-email-paramater\">{EMAIL_ADDRESS}</span> is banned and try open new ticket .</div>\r\n</div>\r\n<div style=\"background: #fef2ef; padding: 15px; margin: 20px; border: 1px solid #eba7a8;\">\r\n<div style=\"font-weight: bold; font-size: 14px; margin-bottom: 5px; color: #983133; text-transform: uppercase;\">Do not reply TO this E-Mail</div>\r\n<div style=\"color: #727376; line-height: 2;\">This is an automated e-mail message sent from our support system. Do not reply to this e-mail as we cannot receive your reply!</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>', '2012-07-22 07:19:19', NULL),
(18, 'ticket-new-admin', '', 'JS Support Ticket: New Tickets Received', '<div style=\"background-color: #f7f7f7; margin: 0; padding: 70px 0; width: 100%;\">\r\n<div style=\"border: 3px dotted #ebecec; width: 600px; display: block; margin: 0 auto; background: #fff;\">\r\n<div style=\"float: left; width: 100%; background: #576cf1; background-repeat: no-repeat, no-repeat, no-repeat; background-position: top left, top right, center center; margin-bottom: 20px;\">\r\n<div style=\"padding: 22px 20px; background: #3e4095; color: #fff; font-size: 18px; font-weight: bold; text-transform: capitalize;\">\r\n<div style=\"display: inline-block;\">JS Support Ticket</div>\r\n<div style=\"float: right; font-weight: bold; font-size: 18px; color: #fff;\">Hello,</div>\r\n</div>\r\n<div style=\"padding: 40px 30px; text-align: center; font-weight: bold; color: #fff; text-transform: capitalize; font-size: 22px;\">New Tickets Received</div>\r\n</div>\r\n<div style=\"padding: 0px;\">\r\n<div style=\"padding-bottom: 20px; border-bottom: 1px solid #dbdbda; background: #f9f9f9; color: #4b4b4d; margin-bottom: 40px;\">\r\n<div style=\"color: #727376; line-height: 2; padding: 17px; text-align: center;\">A new support ticket <strong>{SUBJECT}</strong> has been submitted. Ticket details.</div>\r\n</div>\r\n<div style=\"padding: 20px 20px 10px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda; background: #f9f9f9;\">\r\n<div style=\"font-weight: bold; font-size: 16px; margin-bottom: 10px; color: #4b4b4d;\">Tracking ID: {TRACKINGID}</div>\r\n</div>\r\n<div style=\"padding: 20px 20px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda;\">Email: {EMAIL}</div>\r\n<div style=\"padding: 20px 20px;\">Ticket message: {MESSAGE}</div>\r\n<div style=\"padding: 20px 20px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda;\">You can manage this ticket here:<br />{TICKETURL}</div>\r\n<div style=\"background: #fef2ef; padding: 15px; margin: 20px; border: 1px solid #eba7a8;\">\r\n<div style=\"font-weight: bold; font-size: 14px; margin-bottom: 5px; color: #983133; text-transform: uppercase;\">Do not reply TO this E-Mail</div>\r\n<div style=\"color: #727376; line-height: 2;\">This is an automated e-mail message sent from our support system. Do not reply to this e-mail as we cannot receive your reply!</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>', '2012-07-21 11:08:28', 1),
(2, 'department-new', NULL, 'JS Support Ticket :  New Department {DEPARTMENT_TITLE} has beed received', '<div style=\"background-color: #f7f7f7; margin: 0; padding: 70px 0; width: 100%;\">\r\n<div style=\"border: 3px dotted #ebecec; width: 600px; display: block; margin: 0 auto; background: #fff;\">\r\n<div style=\"float: left; width: 100%; background: #476cf1; background-repeat: no-repeat, no-repeat, no-repeat; background-position: top left, top right, center center; margin-bottom: 20px;\">\r\n<div style=\"padding: 22px 20px; background: #3e4095; color: #fff; font-size: 18px; font-weight: bold; text-transform: capitalize;\">\r\n<div style=\"display: inline-block;\">JS Support Ticket</div>\r\n<div style=\"float: right; font-weight: bold; font-size: 18px; color: #fff;\">Hello Admin,</div>\r\n</div>\r\n<div style=\"padding: 40px 30px; text-align: center; font-weight: bold; color: #fff; text-transform: capitalize; font-size: 22px;\">We receive new department</div>\r\n</div>\r\n<div style=\"padding: 0px;\">\r\n<div style=\"padding-bottom: 20px; border-bottom: 1px solid #dbdbda; background: #f9f9f9; color: #4b4b4d; margin-bottom: 40px;\">\r\n<div style=\"color: #727376; line-height: 2; padding: 17px; text-align: center;\">We receive new department <strong>{DEPARTMENT_TITLE}</strong></div>\r\n</div>\r\n<div style=\"background: #fef2ef; padding: 15px; margin: 20px; border: 1px solid #eba7a8;\">\r\n<div style=\"font-weight: bold; font-size: 14px; margin-bottom: 5px; color: #983133; text-transform: uppercase;\">Do not reply TO this E-Mail</div>\r\n<div style=\"color: #727376; line-height: 2;\">This is an automated e-mail message sent from our support system. Do not reply to this e-mail as we cannot receive your reply!</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>', '2012-07-22 07:15:12', NULL),
(3, 'group-new', NULL, 'JS Support Ticket :  New Group {GROUP_TITLE} has beed received', '<p>Hello Admin ,</p>\r\n<p>We receive new group.</p>\r\n<p><span style=\"color: red;\"><strong>*DO NOT REPLY TO THIS E-MAIL*</strong></span><br />This is an automated e-mail message sent from our support system. Do not reply to this e-mail as we wonot receive your reply!</p>', '2012-07-22 07:17:17', NULL),
(4, 'staff-new', NULL, 'JS Support Ticket:  New Staff Member {STAFF_MEMBER_TITLE} has beed received', '<div style=\"background-color: #f7f7f7; margin: 0; padding: 70px 0; width: 100%;\">\r\n<div style=\"border: 3px dotted #ebecec; width: 600px; display: block; margin: 0 auto; background: #fff;\">\r\n<div style=\"float: left; width: 100%; background: #576cf1; background-repeat: no-repeat, no-repeat, no-repeat; background-position: top left, top right, center center; margin-bottom: 20px;\">\r\n<div style=\"padding: 22px 20px; background: #3e4095; color: #fff; font-size: 18px; font-weight: bold; text-transform: capitalize;\">\r\n<div style=\"display: inline-block;\">JS Support Ticket</div>\r\n<div style=\"float: right; font-weight: bold; font-size: 18px; color: #fff;\">Hello Admin,</div>\r\n</div>\r\n<div style=\"padding: 40px 30px; text-align: center; font-weight: bold; color: #fff; text-transform: capitalize; font-size: 22px;\">We receive new staff member</div>\r\n</div>\r\n<div style=\"padding: 0px;\">\r\n<div style=\"padding-bottom: 20px; border-bottom: 1px solid #dbdbda; background: #f9f9f9; color: #4b4b4d; margin-bottom: 40px;\">\r\n<div style=\"color: #727376; line-height: 2; padding: 17px; text-align: center;\">We receive new staff member <strong>{STAFF_MEMBER_NAME}</strong></div>\r\n</div>\r\n<div style=\"background: #fef2ef; padding: 15px; margin: 20px; border: 1px solid #eba7a8;\">\r\n<div style=\"font-weight: bold; font-size: 14px; margin-bottom: 5px; color: #983133; text-transform: uppercase;\">Do not reply TO this E-Mail</div>\r\n<div style=\"color: #727376; line-height: 2;\">This is an automated e-mail message sent from our support system. Do not reply to this e-mail as we cannot receive your reply!</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>', '2012-07-22 07:17:26', NULL),
(5, 'helptopic-new', NULL, 'JS Support Ticket : New Help Topic {HELPTOPIC_TITLE} has beed received', '<div style=\"background-color: #f7f7f7; margin: 0; padding: 70px 0; width: 100%;\">\r\n<div style=\"border: 3px dotted #ebecec; width: 600px; display: block; margin: 0 auto; background: #fff;\">\r\n<div style=\"float: left; width: 100%; background: #576cf1; background-repeat: no-repeat, no-repeat, no-repeat; background-position: top left, top right, center center; margin-bottom: 20px;\">\r\n<div style=\"padding: 22px 20px; background: #3e4095; color: #fff; font-size: 18px; font-weight: bold; text-transform: capitalize;\">\r\n<div style=\"display: inline-block;\">JS Support Ticket</div>\r\n<div style=\"float: right; font-weight: bold; font-size: 18px; color: #fff;\">Hello Admin,</div>\r\n</div>\r\n<div style=\"padding: 40px 30px; text-align: center; font-weight: bold; color: #fff; text-transform: capitalize; font-size: 22px;\">We receive new help topic</div>\r\n</div>\r\n<div style=\"padding: 0px;\">\r\n<div style=\"padding-bottom: 20px; border-bottom: 1px solid #dbdbda; background: #f9f9f9; color: #4b4b4d; margin-bottom: 40px;\">\r\n<div style=\"color: #727376; line-height: 2; padding: 17px; text-align: center;\">We receive new help topic <strong><span class=\"js-email-paramater\">{HELPTOPIC_TITLE}</span></strong> of department <strong><span class=\"js-email-paramater\">{DEPARTMENT_TITLE}</span></strong></div>\r\n</div>\r\n<div style=\"background: #fef2ef; padding: 15px; margin: 20px; border: 1px solid #eba7a8;\">\r\n<div style=\"font-weight: bold; font-size: 14px; margin-bottom: 5px; color: #983133; text-transform: uppercase;\">Do not reply TO this E-Mail</div>\r\n<div style=\"color: #727376; line-height: 2;\">This is an automated e-mail message sent from our support system. Do not reply to this e-mail as we cannot receive your reply!</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>', '2012-07-22 07:17:34', NULL),
(19, 'lock-tk', NULL, 'JS Support Ticket :  Ticket {TRACKINGID} has been locked', '<div style=\"background-color: #f7f7f7; margin: 0; padding: 70px 0; width: 100%;\">\r\n<div style=\"border: 3px dotted #ebecec; width: 600px; display: block; margin: 0 auto; background: #fff;\">\r\n<div style=\"float: left; width: 100%; background: #576cf1; background-repeat: no-repeat, no-repeat, no-repeat; background-position: top left, top right, center center; margin-bottom: 20px;\">\r\n<div style=\"padding: 22px 20px; background: #3e4095; color: #fff; font-size: 18px; font-weight: bold; text-transform: capitalize;\">\r\n<div style=\"display: inline-block;\">JS Support Ticket</div>\r\n<div style=\"float: right; font-weight: bold; font-size: 18px; color: #fff;\">Dear {USERNAME} ,</div>\r\n</div>\r\n<div style=\"padding: 40px 30px; text-align: center; font-weight: bold; color: #fff; text-transform: capitalize; font-size: 22px;\">Ticket has been locked</div>\r\n</div>\r\n<div style=\"padding: 0px;\">\r\n<div style=\"padding-bottom: 20px; border-bottom: 1px solid #dbdbda; background: #f9f9f9; color: #4b4b4d; margin-bottom: 40px;\">\r\n<div style=\"color: #727376; line-height: 2; padding: 17px; text-align: center;\">Your Ticket <span class=\"js-email-paramater\">{TRACKINGID}</span> has been locked.</div>\r\n</div>\r\n<div style=\"padding: 20px 20px 10px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda; background: #f9f9f9;\">\r\n<div style=\"font-weight: bold; font-size: 16px; margin-bottom: 10px; color: #4b4b4d;\">Tracking ID: <span class=\"js-email-paramater\">{TRACKINGID}</span></div>\r\n</div>\r\n<div style=\"padding: 20px 20px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda;\">Email: {EMAIL}</div>\r\n<div style=\"padding: 20px 20px;\">Username : {USERNAME}</div>\r\n<div style=\"padding: 20px 20px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda;\">Subject : {SUBJECT}</div>\r\n<div style=\"padding: 20px 20px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda;\">You can manage this ticket here:<br /><span class=\"js-email-paramater\">{TICKETURL}</span></div>\r\n<div style=\"background: #fef2ef; padding: 15px; margin: 20px; border: 1px solid #eba7a8;\">\r\n<div style=\"font-weight: bold; font-size: 14px; margin-bottom: 5px; color: #983133; text-transform: uppercase;\">Do not reply TO this E-Mail</div>\r\n<div style=\"color: #727376; line-height: 2;\">This is an automated e-mail message sent from our support system. Do not reply to this e-mail as we cannot receive your reply!</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>', '2012-07-22 07:18:12', NULL),
(20, 'unlock-tk', NULL, 'JS Support Ticket :  Ticket {TRACKINGID} has been unlocked', '<div style=\"background-color: #f7f7f7; margin: 0; padding: 70px 0; width: 100%;\">\r\n<div style=\"border: 3px dotted #ebecec; width: 600px; display: block; margin: 0 auto; background: #fff;\">\r\n<div style=\"float: left; width: 100%; background: #576cf1; background-repeat: no-repeat, no-repeat, no-repeat; background-position: top left, top right, center center; margin-bottom: 20px;\">\r\n<div style=\"padding: 22px 20px; background: #3e4095; color: #fff; font-size: 18px; font-weight: bold; text-transform: capitalize;\">\r\n<div style=\"display: inline-block;\">JS Support Ticket</div>\r\n<div style=\"float: right; font-weight: bold; font-size: 18px; color: #fff;\">Dear {USERNAME} ,</div>\r\n</div>\r\n<div style=\"padding: 40px 30px; text-align: center; font-weight: bold; color: #fff; text-transform: capitalize; font-size: 22px;\">Ticket has been unlocked</div>\r\n</div>\r\n<div style=\"padding: 0px;\">\r\n<div style=\"padding-bottom: 20px; border-bottom: 1px solid #dbdbda; background: #f9f9f9; color: #4b4b4d; margin-bottom: 40px;\">\r\n<div style=\"color: #727376; line-height: 2; padding: 17px; text-align: center;\">Your Ticket <span class=\"js-email-paramater\">{TRACKINGID}</span> has been unlocked.</div>\r\n</div>\r\n<div style=\"padding: 20px 20px 10px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda; background: #f9f9f9;\">\r\n<div style=\"font-weight: bold; font-size: 16px; margin-bottom: 10px; color: #4b4b4d;\">Tracking ID: <span class=\"js-email-paramater\">{TRACKINGID}</span></div>\r\n</div>\r\n<div style=\"padding: 20px 20px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda;\">Email: {EMAIL}</div>\r\n<div style=\"padding: 20px 20px;\">Username : {USERNAME}</div>\r\n<div style=\"padding: 20px 20px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda;\">Subject : {SUBJECT}</div>\r\n<div style=\"padding: 20px 20px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda;\">You can manage ticket here:<br /><span class=\"js-email-paramater\">{TICKETURL}</span></div>\r\n<div style=\"background: #fef2ef; padding: 15px; margin: 20px; border: 1px solid #eba7a8;\">\r\n<div style=\"font-weight: bold; font-size: 14px; margin-bottom: 5px; color: #983133; text-transform: uppercase;\">Do not reply TO this E-Mail</div>\r\n<div style=\"color: #727376; line-height: 2;\">This is an automated e-mail message sent from our support system. Do not reply to this e-mail as we cannot receive your reply!</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>', '2012-07-22 07:18:12', NULL),
(21, 'markprgs-tk', NULL, 'JS Support Ticket:  Yout ticket mark in progress', '<div style=\"background-color: #f7f7f7; margin: 0; padding: 70px 0; width: 100%;\">\r\n<div style=\"border: 3px dotted #ebecec; width: 600px; display: block; margin: 0 auto; background: #fff;\">\r\n<div style=\"float: left; width: 100%; background: #576cf1; background-repeat: no-repeat, no-repeat, no-repeat; background-position: top left, top right, center center; margin-bottom: 20px;\">\r\n<div style=\"padding: 22px 20px; background: #3e4095; color: #fff; font-size: 18px; font-weight: bold; text-transform: capitalize;\">\r\n<div style=\"display: inline-block;\">JS Support Ticket</div>\r\n<div style=\"float: right; font-weight: bold; font-size: 18px; margin-top: 15px; color: #fff;\"> </div>\r\n</div>\r\n<div style=\"padding: 40px 30px; text-align: center; font-weight: bold; color: #fff; text-transform: capitalize; font-size: 22px;\">Ticket Mark in progress</div>\r\n</div>\r\n<div style=\"padding: 0px;\">\r\n<div style=\"padding-bottom: 20px; border-bottom: 1px solid #dbdbda; background: #f9f9f9; color: #4b4b4d; margin-bottom: 40px;\">\r\n<div style=\"color: #727376; line-height: 2; padding: 17px; text-align: center;\">Ticket ID:<span class=\"js-email-paramater\">{TRACKINGID}</span> is Mark in progress.</div>\r\n</div>\r\n<div style=\"padding: 20px 20px 10px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda; background: #f9f9f9;\">\r\n<div style=\"font-weight: bold; font-size: 16px; margin-bottom: 10px; color: #4b4b4d;\">Ticket Subject : {SUBJECT}</div>\r\n</div>\r\n<div style=\"padding: 20px 20px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda;\">You can manage this ticket here:<br /><span class=\"js-email-paramater\">{TICKETURL}</span></div>\r\n<div style=\"background: #fef2ef; padding: 15px; margin: 20px; border: 1px solid #eba7a8;\">\r\n<div style=\"font-weight: bold; font-size: 14px; margin-bottom: 5px; color: #983133; text-transform: uppercase;\">Do not reply TO this E-Mail</div>\r\n<div style=\"color: #727376; line-height: 2;\">This is an automated e-mail message sent from our support system. Do not reply to this e-mail as we cannot receive your reply!</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>', '2012-07-22 07:18:12', NULL),
(22, 'pchnge-tk', NULL, 'JS Support Ticket:  Your ticket priority is change', '<div style=\"background-color: #f7f7f7; margin: 0; padding: 70px 0; width: 100%;\">\r\n<div style=\"border: 3px dotted #ebecec; width: 600px; display: block; margin: 0 auto; background: #fff;\">\r\n<div style=\"float: left; width: 100%; background: #576cf1; background-repeat: no-repeat, no-repeat, no-repeat; background-position: top left, top right, center center; margin-bottom: 20px;\">\r\n<div style=\"padding: 22px 20px; background: #3e4095; color: #fff; font-size: 18px; font-weight: bold; text-transform: capitalize;\">\r\n<div style=\"display: inline-block;\">JS Support Ticket</div>\r\n<div style=\"float: right; font-weight: bold; font-size: 18px; color: #fff;\"> </div>\r\n</div>\r\n<div style=\"padding: 40px 30px; text-align: center; font-weight: bold; color: #fff; text-transform: capitalize; font-size: 22px;\">Ticket priority is changed</div>\r\n</div>\r\n<div style=\"padding: 0px;\">\r\n<div style=\"padding-bottom: 20px; border-bottom: 1px solid #dbdbda; background: #f9f9f9; color: #4b4b4d; margin-bottom: 40px;\">\r\n<div style=\"color: #727376; line-height: 2; padding: 17px; text-align: center;\">Ticket ID: {TRACKINGID} is priority changed and new priority {PRIORITY_TITLE}.</div>\r\n</div>\r\n<div style=\"padding: 20px 20px 10px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda; background: #f9f9f9;\">\r\n<div style=\"font-weight: bold; font-size: 16px; margin-bottom: 10px; color: #4b4b4d;\">Ticket Subject : {SUBJECT}</div>\r\n</div>\r\n<div style=\"padding: 20px 20px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda;\">You can manage this ticket here:<br />{TICKETURL}</div>\r\n<div style=\"background: #fef2ef; padding: 15px; margin: 20px; border: 1px solid #eba7a8;\">\r\n<div style=\"font-weight: bold; font-size: 14px; margin-bottom: 5px; color: #983133; text-transform: uppercase;\">Do not reply TO this E-Mail</div>\r\n<div style=\"color: #727376; line-height: 2;\">This is an automated e-mail message sent from our support system. Do not reply to this e-mail as we cannot receive your reply!</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>', '2012-07-22 07:18:12', NULL),
(23, 'mlnew-tk', NULL, 'JS Support Ticket:  New mail has been sent by {STAFF_MEMBER_NAME}', '<div style=\"background-color: #f7f7f7; margin: 0; padding: 70px 0; width: 100%;\">\r\n<div style=\"border: 3px dotted #ebecec; width: 600px; display: block; margin: 0 auto; background: #fff;\">\r\n<div style=\"float: left; width: 100%; background: #576cf1; background-repeat: no-repeat, no-repeat, no-repeat; background-position: top left, top right, center center; margin-bottom: 20px;\">\r\n<div style=\"padding: 22px 20px; background: #3e4095; color: #fff; font-size: 18px; font-weight: bold; text-transform: capitalize;\">\r\n<div style=\"display: inline-block;\">JS Support Ticket</div>\r\n<div style=\"float: right; font-weight: bold; font-size: 18px; color: #fff;\"> </div>\r\n</div>\r\n<div style=\"padding: 40px 30px; text-align: center; font-weight: bold; color: #fff; text-transform: capitalize; font-size: 22px;\">Internal Mail</div>\r\n</div>\r\n<div style=\"padding: 0px;\">\r\n<div style=\"padding-bottom: 20px; border-bottom: 1px solid #dbdbda; background: #f9f9f9; color: #4b4b4d; margin-bottom: 40px;\">\r\n<div style=\"color: #727376; line-height: 2; padding: 17px; text-align: center;\">New internal mail received.</div>\r\n</div>\r\n<div style=\"padding: 20px 20px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda;\">You can manage this ticket here:<br />{TICKETURL}</div>\r\n<div style=\"background: #fef2ef; padding: 15px; margin: 20px; border: 1px solid #eba7a8;\">\r\n<div style=\"font-weight: bold; font-size: 14px; margin-bottom: 5px; color: #983133; text-transform: uppercase;\">Do not reply TO this E-Mail</div>\r\n<div style=\"color: #727376; line-height: 2;\">This is an automated e-mail message sent from our support system. Do not reply to this e-mail as we cannot receive your reply!</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>', '2012-07-22 07:18:12', NULL);
INSERT INTO `#__js_ticket_emailtemplates` (`id`, `templatefor`, `title`, `subject`, `body`, `created`, `status`) VALUES
(24, 'mlrep-tk', NULL, 'JS Support Ticket:  New reply has been sent by {STAFF_MEMBER_NAME}', '<div style=\"background-color: #f7f7f7; margin: 0; padding: 70px 0; width: 100%;\">\r\n<div style=\"border: 3px dotted #ebecec; width: 600px; display: block; margin: 0 auto; background: #fff;\">\r\n<div style=\"float: left; width: 100%; background: #576cf1; background-repeat: no-repeat, no-repeat, no-repeat; background-position: top left, top right, center center; margin-bottom: 20px;\">\r\n<div style=\"padding: 22px 20px; background: #3e4095; color: #fff; font-size: 18px; font-weight: bold; text-transform: capitalize;\">\r\n<div style=\"display: inline-block;\">JS Support Ticket</div>\r\n<div style=\"float: right; font-weight: bold; font-size: 18px; color: #fff;\"> </div>\r\n</div>\r\n<div style=\"padding: 40px 30px; text-align: center; font-weight: bold; color: #fff; text-transform: capitalize; font-size: 22px;\">New reply has been sent</div>\r\n</div>\r\n<div style=\"padding: 0px;\">\r\n<div style=\"padding-bottom: 20px; border-bottom: 1px solid #dbdbda; background: #f9f9f9; color: #4b4b4d; margin-bottom: 40px;\">\r\n<div style=\"color: #727376; line-height: 2; padding: 17px; text-align: center;\">New reply has been sent by the <span class=\"js-email-paramater\">{STAFF_MEMBER_NAME}</span></div>\r\n</div>\r\n<div style=\"padding: 20px 20px 10px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda; background: #f9f9f9;\">\r\n<div style=\"font-weight: bold; font-size: 16px; margin-bottom: 10px; color: #4b4b4d;\">Mail Subject : {SUBJECT}</div>\r\n</div>\r\n<div style=\"padding: 20px 20px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda;\">Message : {MESSAGE}</div>\r\n<div style=\"background: #fef2ef; padding: 15px; margin: 20px; border: 1px solid #eba7a8;\">\r\n<div style=\"font-weight: bold; font-size: 14px; margin-bottom: 5px; color: #983133; text-transform: uppercase;\">Do not reply TO this E-Mail</div>\r\n<div style=\"color: #727376; line-height: 2;\">This is an automated e-mail message sent from our support system. Do not reply to this e-mail as we cannot receive your reply!</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>', '2012-07-22 07:18:12', NULL),
(25, 'ticket-staff', '', 'JS Support Ticket: New Ticket', 'Sucess: Ticket Submitted\r\n\r\nNew ticket <strong>{SUBJECT}</strong> has been submitted with the following details.\r\n\r\nTracking ID: {TRACKINGID}\r\n\r\nEmail ID: {EMAIL}\r\n\r\nTicket message: {MESSAGE}\r\n\r\nHelp Topic: {HELP_TOPIC}\r\n\r\nYou can view the status of your ticket here:\r\n{TICKETURL}\r\n\r\nYou will receive an e-mail notification when our staff replies to your ticket.\r\n\r\n<span style=\"color: red;\"><strong>*DO NOT REPLY TO THIS E-MAIL*</strong></span>\r\nThis is an automated e-mail message sent from our support system. Do not reply to this e-mail as we wonot receive your reply!', '2012-07-21 11:09:00', 1),
(26, 'mail-rpy-closed', '', 'JS Tickets: Ticket has been closed', '<div style=\"background-color: #f7f7f7; margin: 0; padding: 70px 0; width: 100%;\">\r\n<div style=\"border: 3px dotted #ebecec; width: 600px; display: block; margin: 0 auto; background: #fff;\">\r\n<div style=\"float: left; width: 100%; background: #576cf1; background-repeat: no-repeat, no-repeat, no-repeat; background-position: top left, top right, center center; margin-bottom: 20px;\">\r\n<div style=\"padding: 22px 20px; background: #3e4095; color: #fff; font-size: 18px; font-weight: bold; text-transform: capitalize;\">\r\n<div style=\"display: inline-block;\">JS Support Ticket</div>\r\n<div style=\"float: right; font-weight: bold; font-size: 18px; color: #fff;\"> </div>\r\n</div>\r\n<div style=\"padding: 40px 30px; text-align: center; font-weight: bold; color: #fff; text-transform: capitalize; font-size: 22px;\">Ticket has been closed</div>\r\n</div>\r\n<div style=\"padding: 0px;\">\r\n<div style=\"padding-bottom: 20px; border-bottom: 1px solid #dbdbda; background: #f9f9f9; color: #4b4b4d; margin-bottom: 40px;\">\r\n<div style=\"color: #727376; line-height: 2; padding: 17px; text-align: center;\">Your ticket <span class=\"js-email-paramater\">{TICKET_SUBJECT}</span> has been closed.</div>\r\n</div>\r\n<div style=\"padding: 20px 20px 10px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda; background: #f9f9f9;\">\r\n<div style=\"font-weight: bold; font-size: 16px; margin-bottom: 10px; color: #4b4b4d;\">You can not reply to a closed ticket</div>\r\n</div>\r\n<div style=\"background: #fef2ef; padding: 15px; margin: 20px; border: 1px solid #eba7a8;\">\r\n<div style=\"font-weight: bold; font-size: 14px; margin-bottom: 5px; color: #983133; text-transform: uppercase;\">Do not reply TO this E-Mail</div>\r\n<div style=\"color: #727376; line-height: 2;\">This is an automated e-mail message sent from our support system. Do not reply to this e-mail as we cannot receive your reply!</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>', '2017-04-03 11:09:00', 1),
(27, 'mail-feedback', '', 'JS Tickets: Give Us Your Feedback', '<div style=\"background-color: #f7f7f7; margin: 0; padding: 70px 0; width: 100%;\">\r\n<div style=\"border: 3px dotted #ebecec; width: 600px; display: block; margin: 0 auto; background: #fff;\">\r\n<div style=\"float: left; width: 100%; background: #576cf1; background-repeat: no-repeat, no-repeat, no-repeat; background-position: top left, top right, center center; margin-bottom: 20px;\">\r\n<div style=\"padding: 22px 20px; background: #3e4095; color: #fff; font-size: 18px; font-weight: bold; text-transform: capitalize;\">\r\n<div style=\"display: inline-block;\">JS Support Ticket</div>\r\n<div style=\"float: right; font-weight: bold; font-size: 18px; color: #fff;\">Dear {USER_NAME},</div>\r\n</div>\r\n<div style=\"padding: 40px 30px; text-align: center; font-weight: bold; color: #fff; text-transform: capitalize; font-size: 22px;\">Give Us Your Feedback</div>\r\n</div>\r\n<div style=\"padding: 0px;\">\r\n<div style=\"padding-bottom: 20px; border-bottom: 1px solid #dbdbda; background: #f9f9f9; color: #4b4b4d; margin-bottom: 40px;\">\r\n<div style=\"color: #727376; line-height: 2; padding: 17px; text-align: center;\">Your ticket <span class=\"js-email-paramater\">{TICKET_SUBJECT}</span> having tracking id <span class=\"js-email-paramater\">{TRACKING_ID}</span> has been closed on <span class=\"js-email-paramater\">{CLOSE_DATE}</span>. We would really appreciate if you took the time to tell us how well our staff member helped you in your problem..</div>\r\n</div>\r\n<div style=\"padding: 20px 20px 10px; border-top: 1px solid #dbdbda; border-bottom: 1px solid #dbdbda; background: #f9f9f9;\">\r\n<div style=\"font-weight: bold; font-size: 16px; margin-bottom: 10px; color: #4b4b4d;\">{LINK}link text{/LINK}</div>\r\n</div>\r\n<div style=\"background: #fef2ef; padding: 15px; margin: 20px; border: 1px solid #eba7a8;\">\r\n<div style=\"font-weight: bold; font-size: 14px; margin-bottom: 5px; color: #983133; text-transform: uppercase;\">Do not reply TO this E-Mail</div>\r\n<div style=\"color: #727376; line-height: 2;\">This is an automated e-mail message sent from our support system. Do not reply to this e-mail as we cannot receive your reply!</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>', '2017-04-03 11:09:00', 1),
(28, 'delete-user-data', '', '{SITETITLE}: Delete User Data', '<div style=\"background-color: #f7f7f7; margin: 0; padding: 70px 0; width: 100%;\">\r\n<div style=\"border: 3px dotted #ebecec; width: 600px; display: block; margin: 0 auto; background: #fff;\">\r\n<div style=\"float: left; width: 100%; background: #576cf1; background-repeat: no-repeat, no-repeat, no-repeat; background-position: top left, top right, center center; margin-bottom: 20px;\">\r\n<div style=\"padding: 22px 20px; background: #3e4095; color: #fff; font-size: 18px; font-weight: bold; text-transform: capitalize;\">\r\n<div style=\"display: inline-block;\">JS Support Ticket</div>\r\n<div style=\"float: right; font-weight: bold; font-size: 18px; color: #fff;\"> </div>\r\n</div>\r\n<div style=\"padding: 40px 30px; text-align: center; font-weight: bold; color: #fff; text-transform: capitalize; font-size: 22px;\"><span style=\"font-size: 12.16px;\"><strong>{SITETITLE}: Data Delete request</strong></span></div>\r\n</div>\r\n<div style=\"padding: 0px;\">\r\n<div style=\"padding-bottom: 20px; border-bottom: 1px solid #dbdbda; background: #f9f9f9; color: #4b4b4d; margin-bottom: 40px;\">\r\n<div style=\"color: #727376; line-height: 2; padding: 17px; text-align: center;\">Your data delete request has been received..</div>\r\n</div>\r\n<div style=\"background: #fef2ef; padding: 15px; margin: 20px; border: 1px solid #eba7a8;\">\r\n<div style=\"font-weight: bold; font-size: 14px; margin-bottom: 5px; color: #983133; text-transform: uppercase;\">Do not reply TO this E-Mail</div>\r\n<div style=\"color: #727376; line-height: 2;\">This is an automated e-mail message sent from our support system. Do not reply to this e-mail as we cannot receive your reply!</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>', '2017-04-03 11:09:00', 1),
(29, 'delete-user-data-admin', '', '{SITETITLE}: User erase data request', '<div style=\"background-color: #f7f7f7; margin: 0; padding: 70px 0; width: 100%;\">\r\n<div style=\"border: 3px dotted #ebecec; width: 600px; display: block; margin: 0 auto; background: #fff;\">\r\n<div style=\"float: left; width: 100%; background: #576cf1; background-repeat: no-repeat, no-repeat, no-repeat; background-position: top left, top right, center center; margin-bottom: 20px;\">\r\n<div style=\"padding: 22px 20px; background: #3e4095; color: #fff; font-size: 18px; font-weight: bold; text-transform: capitalize;\">\r\n<div style=\"display: inline-block;\">JS Support Ticket</div>\r\n<div style=\"float: right; font-weight: bold; font-size: 18px; color: #fff;\"> </div>\r\n</div>\r\n<div style=\"padding: 40px 30px; text-align: center; font-weight: bold; color: #fff; text-transform: capitalize; font-size: 22px;\"><span style=\"font-size: 12.16px;\"><strong>{SITETITLE}: User erase data request</strong></span></div>\r\n</div>\r\n<div style=\"padding: 0px;\">\r\n<div style=\"padding-bottom: 20px; border-bottom: 1px solid #dbdbda; background: #f9f9f9; color: #4b4b4d; margin-bottom: 40px;\">\r\n<div style=\"color: #727376; line-height: 2; padding: 17px; text-align: center;\">{USERNAME} has been submitted a request for erasing data.</div>\r\n</div>\r\n<div style=\"background: #fef2ef; padding: 15px; margin: 20px; border: 1px solid #eba7a8;\">\r\n<div style=\"font-weight: bold; font-size: 14px; margin-bottom: 5px; color: #983133; text-transform: uppercase;\">Do not reply TO this E-Mail</div>\r\n<div style=\"color: #727376; line-height: 2;\">This is an automated e-mail message sent from our support system. Do not reply to this e-mail as we cannot receive your reply!</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>', '2017-04-03 11:09:00', 1),
(30, 'user-data-deleted', '', '{SITETITLE}: Data deleted successfully', '<div style=\"background-color: #f7f7f7; margin: 0; padding: 70px 0; width: 100%;\">\r\n<div style=\"border: 3px dotted #ebecec; width: 600px; display: block; margin: 0 auto; background: #fff;\">\r\n<div style=\"float: left; width: 100%; background: #576cf1; background-repeat: no-repeat, no-repeat, no-repeat; background-position: top left, top right, center center; margin-bottom: 20px;\">\r\n<div style=\"padding: 22px 20px; background: #3e4095; color: #fff; font-size: 18px; font-weight: bold; text-transform: capitalize;\">\r\n<div style=\"display: inline-block;\">JS Support Ticket</div>\r\n<div style=\"float: right; font-weight: bold; font-size: 18px; color: #fff;\"> </div>\r\n</div>\r\n<div style=\"padding: 40px 30px; text-align: center; font-weight: bold; color: #fff; text-transform: capitalize; font-size: 22px;\">Data deleted successfully</div>\r\n</div>\r\n<div style=\"padding: 0px;\">\r\n<div style=\"padding-bottom: 20px; border-bottom: 1px solid #dbdbda; background: #f9f9f9; color: #4b4b4d; margin-bottom: 40px;\">\r\n<div style=\"color: #727376; line-height: 2; padding: 17px; text-align: center;\">Your data has been deleted successfully.</div>\r\n</div>\r\n<div style=\"background: #fef2ef; padding: 15px; margin: 20px; border: 1px solid #eba7a8;\">\r\n<div style=\"font-weight: bold; font-size: 14px; margin-bottom: 5px; color: #983133; text-transform: uppercase;\">Do not reply TO this E-Mail</div>\r\n<div style=\"color: #727376; line-height: 2;\">This is an automated e-mail message sent from our support system. Do not reply to this e-mail as we cannot receive your reply!</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>', '2017-04-03 11:09:00', 1);

CREATE TABLE IF NOT EXISTS `#__js_ticket_priorities` (
	`id` int(11) NOT NULL AUTO_INCREMENT, 
	`priority` varchar(60) DEFAULT NULL, 
	`prioritycolour` varchar(7) DEFAULT NULL, 
	`priorityurgency` int(1) DEFAULT NULL, 
    `overduetypeid` int(11) DEFAULT NULL,
    `overdueinterval` int(11) DEFAULT NULL, 
	`ispublic` varchar(45) DEFAULT NULL, 
	`isdefault` tinyint(1) DEFAULT NULL, 
	`status` tinyint(4) NOT NULL DEFAULT '0', 
	PRIMARY KEY (`id`) ) ENGINE=MyISAM AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

INSERT INTO `#__js_ticket_priorities` VALUES (1,'Normal','#00a650',NULL,1,2,'1',1,1),
(2,'Low','#00aeef',NULL,1,3,'1',0,1),
(3,'High','#ee1d24',NULL,1,1,'1',0,1);

CREATE TABLE IF NOT EXISTS `#__js_ticket_replies` (
	`id` int(11) NOT NULL AUTO_INCREMENT, 
	`ticketid` int(11) DEFAULT NULL, 
	`name` varchar(50) DEFAULT NULL, 
	`message` text DEFAULT NULL, 
	`staffid` int(11) DEFAULT NULL, 
	`rating` enum('1','5') DEFAULT NULL, 
	`status` tinyint(1) DEFAULT NULL, 
	`created` datetime DEFAULT NULL, 
	`ticketviaemail` tinyint(1) NOT NULL DEFAULT '0', 
	`mergemessage` TINYINT(1) NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`) ) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `#__js_ticket_system_errors` (
	`id` int(11) NOT NULL AUTO_INCREMENT, 
	`uid` int(11) DEFAULT NULL, 
	`error` text DEFAULT NULL, 
	`isview` tinyint(1) DEFAULT '0', 
	`created` datetime DEFAULT NULL, 
	PRIMARY KEY (`id`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `#__js_ticket_tickets` (
	`id` int(11) NOT NULL AUTO_INCREMENT, 
	`uid` int(11) DEFAULT NULL, 
	`ticketid` varchar(25) DEFAULT NULL, 
	`departmentid` int(11) DEFAULT NULL, 
	`priorityid` int(11) DEFAULT NULL, 
	`staffid` int(11) DEFAULT NULL, 
	`email` varchar(255) DEFAULT NULL, 
	`name` varchar(100) DEFAULT NULL, 
	`subject` varchar(255) DEFAULT NULL, 
	`message` text DEFAULT NULL, 
	`helptopicid` int(11) DEFAULT NULL, 
	`phone` varchar(100) DEFAULT NULL, 
	`phoneext` varchar(20) DEFAULT NULL, 
	`status` tinyint(1) DEFAULT NULL, 
	`isoverdue` tinyint(1) DEFAULT NULL, 
	`isanswered` tinyint(1) NOT NULL DEFAULT '0', 
	`duedate` datetime DEFAULT NULL, 
	`reopened` datetime DEFAULT NULL, 
	`closed` datetime DEFAULT NULL, 
	`lastreply` datetime DEFAULT NULL, 
	`created` datetime DEFAULT NULL, 
	`update` datetime DEFAULT NULL, 
	`lock` tinyint(4) NOT NULL DEFAULT '0', 
	`ticketviaemail` tinyint(1) NOT NULL DEFAULT '0',
	`ticketviaemail_id` INT(11) DEFAULT NULL,	
	`attachmentdir` varchar(50) NOT NULL,
	`feedbackemail` TINYINT DEFAULT NULL,
	`mergestatus` TINYINT(4) NOT NULL DEFAULT '0',
	`mergewith` INT(11) DEFAULT NULL,
	`mergenote` TEXT DEFAULT NULL,
	`mergedate` datetime DEFAULT NULL,
	`multimergeparams` TEXT DEFAULT NULL,
	`mergeuid` INT(11) DEFAULT NULL,
	`params` longtext DEFAULT NULL,
	`hash` varchar(200) COLLATE 'utf8_general_ci' DEFAULT NULL,
	PRIMARY KEY (`id`) ) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `#__js_ticket_fieldsordering` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `field` varchar(50) NOT NULL,
  `fieldtitle` varchar(50) DEFAULT NULL,
  `ordering` int(11) DEFAULT NULL,
  `section` varchar(20) DEFAULT NULL,
  `fieldfor` tinyint(2) DEFAULT NULL,
  `published` tinyint(1) DEFAULT NULL,
  `sys` tinyint(1) NOT NULL DEFAULT '0',
  `cannotunpublish` tinyint(1) NOT NULL DEFAULT '0',
  `required` tinyint(1) NOT NULL DEFAULT '0',
  `isuserfield` TINYINT DEFAULT NULL,
  `depandant_field` VARCHAR( 250 ) DEFAULT NULL,
  `showonlisting` TINYINT DEFAULT NULL,
  `search_user` TINYINT DEFAULT NULL,
  `userfieldparams` LONGTEXT DEFAULT NULL,
  `userfieldtype` VARCHAR( 250 ) DEFAULT NULL,
  `size` VARCHAR( 200 ) DEFAULT NULL,
  `maxlength` VARCHAR( 200 ) DEFAULT NULL,
  `cols` VARCHAR( 200 ) DEFAULT NULL,
  `rows` VARCHAR( 200 ) DEFAULT NULL,
  `isvisitorpublished` TINYINT DEFAULT NULL,
  `search_visitor` TINYINT DEFAULT NULL,
  `cannotsearch` TINYINT DEFAULT NULL,
  `cannotshowonlisting` TINYINT DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fieldordering_filedfor` (`fieldfor`)
) ENGINE=MyISAM AUTO_INCREMENT=25 DEFAULT CHARSET=utf8;

INSERT INTO `#__js_ticket_fieldsordering` (`id`, `field`, `fieldtitle`, `ordering`, `section`, `fieldfor`, `published`, `sys`, `cannotunpublish`, `required`, `size`, `maxlength`, `cols`, `rows`, `isuserfield`, `userfieldtype`, `depandant_field`, `showonlisting`, `cannotshowonlisting`, `search_user`, `cannotsearch`, `isvisitorpublished`, `search_visitor`, `userfieldparams`) VALUES 
(1, 'email', 'Email Address', 2, '10', 1, 1, 0, 1, 1, '50', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL), 
(2, 'users', 'User', 1, '10', 1, 1, 0, 0, 0, '50', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL), 
(3, 'fullname', 'Full Name', 4, '10', 1, 1, 0, 1, 1, '50', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL), 
(4, 'phone', 'Phone', 5, '10', 1, 1, 0, 0, 0, '50', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL), 
(5, 'phoneext', 'Phone Ext', 6, '10', 1, 0, 0, 0, 0, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, 1, 1, NULL, NULL),
(6, 'department', 'Department', 7, '10', 1, 1, 0, 0, 0, '50', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL), 
(7, 'helptopic', 'Help Topic', 8, '10', 1, 1, 0, 0, 0, '50', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL), 
(8, 'priority', 'Priority', 3, '10', 1, 1, 0, 1, 1, '50', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL), 
(9, 'subject', 'Subject', 10, '10', 1, 1, 0, 1, 1, '50', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL), 
(10, 'premade', 'Premade', 9, '10', 1, 1, 0, 0, 0, '50', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL), 
(11, 'issuesummary', 'Issue Summary', 11, '10', 1, 1, 0, 1, 1, '50', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL), 
(12, 'attachments', 'Attachments', 12, '10', 1, 1, 0, 0, 0, '50', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL), 
(13, 'internalnotetitle', 'Internal Note Title', 13, '10', 1, 1, 0, 0, 0, '50', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL), 
(14, 'assignto', 'Assign To', 14, '10', 1, 1, 0, 0, 0, '50', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL), 
(15, 'duedate', 'Due Date', 15, '10', 1, 1, 0, 0, 0, '50', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL), 
(16, 'status', 'Status', 16, '10', 1, 1, 0, 0, 0, '50', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL),
(17, 'rating', 'Rating', '1', '0', '2', '1', '0', '0', '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL, NULL),
(18, 'remarks', 'Remarks', '2', '10', '2', '1', '0', '0', '0', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', '0', '0', '0');

CREATE TABLE IF NOT EXISTS `#__js_ticket_erasedatarequests` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uid` int(11) NOT NULL,
  `subject` varchar(250) NOT NULL,
  `message` text NOT NULL,
  `status` int(11) NOT NULL,
  `created` datetime NOT NULL,
  PRIMARY KEY (`id`) 
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
